version: "3.8"
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
    networks:
      - reverse-proxy

  gateway:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=192.168.178.35
    networks:
      - reverse-proxy

  app1:
    image: jwilder/whoami
    networks:
      - reverse-proxy

  app2:
    image: jwilder/whoami
    networks:
      - reverse-proxy
    expose:
      - "8000"
    environment:
      - PORT=8000
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=8000

networks:
  reverse-proxy: