version: '3'
services:

  backend:
    build: Backend
    command: npm run start
    volumes:
      - ./Backend/app:/usr/app/
      - ./Backend/app/node_modules:/usr/app/node_modules
    env_file: .env
    ports:
      - ${BACKEND_PORT}
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=${PATH}${BACKEND_PATH}
      - VIRTUAL_PORT=${BACKEND_PORT}
    networks:
      - topDomainProxy

  frontend:
    env_file: .env
    build: Frontend
    command: npm run deploy:web:local
    volumes:
      - ./Frontend/app:/usr/app/
      - ./Frontend/app/node_modules:/usr/app/node_modules
      - ./Frontend/app/web-build:/usr/app/web-build
    expose:
      - ${FRONTEND_PORT}
    environment:
      - BACKEND_URL=${DOMAIN_PRE}://${HOST}${PATH}${BACKEND_PATH}
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=${PATH}${FRONTEND_PATH}
    networks:
      - topDomainProxy

networks:
  mycustomNetwork:
  topDomainProxy:
    external: true